- src/felles-komponenter/faner/vedlegg.js
- src/felles-komponenter/faner/vedlegg.less
- src/sider/forside.js
- src/sider/forside.less
Litt styling justering + kommentert ut "Opprett sak" fane som ikke skal vises ennå
> Eux 600 styling

- src/sider/opprettsak.js
- src/sider/personsok.js
**OBS: Merges inn til opprinnelig EUX-667.**
- Flickrer ikke lenger ved klikk
- "Dobbelt" klikk-issue er løst.
- Oppdatert validetring av sokeresultat til å kreve fornavn og etternavn i payload.
> EUX-667: Fikset personsøk opp mot validering

- src/felles-komponenter/skjema/customFamileRelasjoner/familierelasjoner.less
- src/sider/opprettsak.js
- src/sider/opprettsak.less
Diverse haste-fikset for bedre layout under utvikling. Finjusteringer kommer senere.
> EUX-667: Fikset layout og styling

- Jenkinsfile
Dette løser problemer med kolliderende byggnumre ved bygging fra
forskjellige greiner (de starter alle på det samme nummeret) på Jenkins.
> EUX-669: Bare deploy til Maven på hovedgreina.

- src/felles-komponenter/skjema/customFamileRelasjoner/index.js
- src/utils/dato.js
Fikset vask og validering ved onBlur.
> EUX-682: Fikset vasking og validering av dato.

- src/felles-komponenter/skjema/customFamileRelasjoner/familierelasjoner.less
- src/felles-komponenter/skjema/customFamileRelasjoner/index.js
- src/sider/opprettsak.js
- src/sider/opprettsak.less
- src/sider/personsok.js
- src/sider/personsok.less
- Endret layout og lesbarhet i paneler.
- Allerede tillagte familierelasjoner fjernes fra TPS-listen.
- Skjema for spesialrelasjoner (utlandet) tømmes etter innlegg.
- Formattering av datoer til norsk format.
- Flyttet fødselsdato for bedre alignment.
> EUX-680 forbedring av styling

- src/felles-komponenter/statuslinje/statuslinje.js
- src/sider/dokumentsok.js
- src/sider/dokumentsok.less
- src/sider/vedlegg.js
- src/sider/vedlegg.less
- Justert spinnerplassering
- Flyttet søkeknapp
- Lagt inn lenke ved opprettet vedlegg.
- Disablet send vedlegg ved vent på svar.
- Justert plassering av hjelpeknapp.
- Diverse mindre justeringer.
> EUX-681: Justert layout og lagt til lenke ved opprettet vedlegg.

- src/ducks/rinasak/operations.js
- src/felles-komponenter/skjema/customFamileRelasjoner/index.js
- src/proptypes/familierelasjon.js
- src/sider/opprettsak.js
- src/utils/dato.js
- src/utils/dato.test.js
- src/utils/kodeverk.js
Rettet følgende:
- Dato skal alltid tastes inn med år, måned og dag. Eks:  YYYYMMDD, YYMMDD, YYYY.MM.DD osv.
- Dato må sendes inn i formatet YYYY-MM-DD
- Custom familierelasjoner må registreres med nasjonalitet. Lagt inn nedtrekk for dette.
- I tillegg noe koderydding, samt lagt inn utils for kodeverk fra Melosys.
> HOTFIX: Datoproblemer og lagt til nasjonalitet

- package.json
- yarn.lock
4.4.0 => 5.0.0, pga 4.4.0  er slettet fra repo.
> EUX-1244 Oppgradering av react-router-dom 

- Jenkinsfile
> EUX-1367 Update Jenkinsfile to build "master" as main branch

- src/sider/personsok.js
> EUX-1358_personsokskjema_laases_paa_onKeyUp

- src/sider/sak/fagsaker.js
dersom fagsakNr er null, så blir saksID benyttet.
> EUX-1476 nedtrekksliste for fagsak skal fagsak nr vises

- src/felles-komponenter/skjema/PersonOgFamilieRelasjoner/AnnenRelatertTPSPerson.js
- Fjernet funksjon for å generere Nav.Input element for å hindre unødvendig re-render.
> Eux 1375 inputfelt for tps personsok mister fokus

- package.json
Added kodemaps to PRELOAD => redux => store
> DEVOPS Updated eessi-kodeverk => 0.5.0.

- package.json
- src/sider/ukjentSide.js
- src/sider/ukjentSide.test.js
* Endret liten feil på AlertStripe type
> EUX-1830 unit tester ukjent side

- cypress/integration/eux_web_app/opprettsak/behandlingstema_spec.js
- package.json
* Mest sannsynlig tredjeparts depecency jQuery feil se issue https://github.com/cypress-io/cypress/issues/5449
* Rettet liten feil i referanse til en kode i en av testene
> EUX-1942 Nedgradering av cypress

- package.json
- yarn.lock
Nytt behandlingstema "OMS Omsorgs-, pleie- og opplæringspenger" for horizontal
> EUX-1965 Nytt behandlingstema OMS i fagområde horizontal

- cypress/integration/eux_web_app/opprettsak/schema_spec.js
- cypress/integration/eux_web_app/vedlegg/schema_spec.js
- cypress/integration/eux_web_app/vedlegg/vedleggsinformasjon_spec.js
- package.json
- src/sider/dokumentsok.js
- src/sider/opprettsak.js
- src/sider/vedlegg.js
* Bump av cypress 3.4.0 -> 3.6.0
* Tester for vedlegg og opprett endret til å benytte XHR i stedet for fetch
> EUX-1945 E2E vedlegg

- Jenkinsfile
*CYPRESS_INSTALL_BINARY=0 for å stoppe nedlasting av cypress binanry
> EUX-2000 pipeline fix

- public/manifest.json
- scripts/patchinit.js
> EUX-1998 korrekt app navn

- CODEOWNERS
endret codeowners til det resten av våre repoer bruker.
> chore(repo): codeowners

- public/locales/nb/validation.json
- src/applications/SvarSed/AktivitetOgTrygdeperioder/validation.ts
- **validation**
- **fjern doc**
> 235 mangler validering på perioder for inaktivitet
